name: Go Format Check

on: pull_request

jobs:
  gofmt:
    name: Verify Go Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - run: |
          gofmt -l .
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go code is not properly formatted."
            exit 1
          fi
